# Representations des graphes

In [1]:
g = {"A":["B","C"], "B":["A"], "C":["A"]}

Répondez aux questions suivantes :
- g est-il une représentation valide d'un graphe ? d'un arbre ?
- quel est le degré du sommet "A" ? quel est le degré de g ?
- g est-il cyclique ?
- g est-il orienté ?
- quel est la taille de la clique maximale de g ?

Représentez g sous forme de matrice d'adjacence :

In [2]:
import numpy as np
g2 = np.array([[0,1,1],[1,0,0],[1,0,0]])
g2

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

# Manipulation de graphe

pour chacune des représentation ci-dessus, écrivez la méthode get_children(g, n) retournant la liste des fils de n dans g

In [3]:
def get_children(g, n):
    if isinstance(g, dict):
        return g[n]
    else:
        return list(np.where(g[n] >0)[0])

In [4]:
get_children(g,"A")

['B', 'C']

In [5]:
get_children(g2, 0)

[1, 2]

pour la representation de votre choix, coder les méthodes permettant:
- d'ajouter un sommet
- d'ajouter une arrete

In [6]:
def add_node(g, n):
    if isinstance(g, dict):
        g[n] = []
        return g
    else:
        g2 = np.zeros((n, n))
        g2[:-1, :-1] = g
        return g2
        

In [7]:
add_node(g, "D")

{'A': ['B', 'C'], 'B': ['A'], 'C': ['A'], 'D': []}

In [8]:
g2 = add_node(g2, 4)
g2

array([[0., 1., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
def add_edge(g, n1, n2):
    if isinstance(g, dict):
        if n2 not in g[n1]:
            g[n1].append(n2)
    else:
        g[n1, n2] = 1

In [10]:
add_edge(g, 'A', 'D')
g

{'A': ['B', 'C', 'D'], 'B': ['A'], 'C': ['A'], 'D': []}

In [11]:
add_edge(g2, 0, 3)
g2

array([[0., 1., 1., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Parcours en largeur et en profondeur

Votre robot cherche à parcourir un labyrinthe décrit par un graphe orienté pouvant être cyclique (vous pouvez tourner en rond si vous parcourez "naivement")
- quel est le type de parcours adapté pour résoudre ce problème ?
- Implémentez la méthode find_exit(g, start, finish), ou g est un graphe, start la case de départ et f celle d'arrivée, permettant de trouver à coup sur la sortie.
- utiliser la representation par matrie d'adjacence pour pouvoir le tester avec la méthode proposée ci-dessous
- astuce : si vous utiliser la methode get_child définie plus haut, vous n'avez pas besoin de reflechir au type de graphe que vous manipulez !
- conseil : ne l'implémentez pas de manière récursive, une boucle suffit (et sera plus simple à debugguer !)

In [12]:
def find_exit(g, start, finish):
    visited = set()
    to_visit = [start]
    
    while len(to_visit)> 0:
        node_visited = to_visit.pop(-1)  # visite et enleve le dernier element
        
        print("visiting sommet ", node_visited)
        children = get_children(g, node_visited)
        if finish in children:
            print("Found the exit")
            return 
        
        new_nodes = [child for child in children if not (child in visited) 
                     and not (child in to_visit)]
        to_visit += new_nodes
        
        visited.add(node_visited)
    print("exit not found")
find_exit(g, "A", "D")

visiting sommet  A
Found the exit


In [13]:
def generate_random_graph(n_sommet, edge_chance):
    return (np.random.randint(low=0, high=int(1/edge_chance)+1, size=(n_sommet,n_sommet),)*edge_chance).astype(int)

g_rand = generate_random_graph(100, 0.05)

find_exit(g_rand, 0, 99)

visiting sommet  0
visiting sommet  94
visiting sommet  95
visiting sommet  86
visiting sommet  74
visiting sommet  92
visiting sommet  93
visiting sommet  82
visiting sommet  48
visiting sommet  83
visiting sommet  39
visiting sommet  90
visiting sommet  97
visiting sommet  23
visiting sommet  53
visiting sommet  91
Found the exit


Imaginez maintenant que votre graphe représente une suite d'état aux echecs, et que vous souhaitiez
trouver l'état permettant de gagner le plus vite possible.
- quelles conditions cela à il sur le nombre de sommets de sortie possible ?
- implémentez le parcours vous permettant de trouver la réponse le plus rapidement possible
- astuce: passer d'un parcours en profondeur à un parcours en largeur ne demande que de changer une ligne de code !

In [14]:
def find_shortest_win(g, start, win_list):
    visited = set()
    to_visit = [start]
    n_room_explored = 0
    while len(to_visit)> 0:
        
        node_visited = to_visit.pop(0)  # visite et enleve le dernier element
        n_room_explored += 1
        print("visiting sommet ", node_visited)
        children = get_children(g, node_visited)
        for child in children:
            if child in win_list:
                print("Found the winning state ",child, " in ", n_room_explored, " steps")
                return child
        new_nodes = [child for child in children if not (child in visited) 
                     and not (child in to_visit)]
        to_visit += new_nodes
        visited.add(node_visited)
    print("No way to win found")

In [15]:
find_shortest_win(g_rand, 0, [5, 3, 99])

visiting sommet  0
visiting sommet  14
visiting sommet  26
visiting sommet  36
Found the winning state  3  in  4  steps


3