# Part 1 : livecoding

### - Charger numpy

In [6]:
import numpy as np

### 1) Toutes les méthodes d'initialisation
- initialiser un tableau rempli de zeros de 10 éléments

In [7]:
x, y = 10, 1
matrix = [[0 for x in range(x)] for y in range(y)]
print(matrix)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


- Initialiser une matrice remplie de zeros !!! d'entiers !!! de dimensions 5,10

In [45]:
# x, y = 10, 5
# matrix = [[0 for x in range(x)] for y in range(y)]
matrix = np.zeros((5,10), dtype=int)
print(matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


- créer un tableau à partir d'une liste de 100 éléments contenant tout les entiers entre 1 et 100. On pourrait le faire directement avec numpy également.

In [51]:
np.array(np.arange(1, 101), dtype=int)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

- initialiser une matrice de taille (2,2,3) de valeur constante 42

In [52]:
np.full((2,2,3), 42)

array([[[42, 42, 42],
        [42, 42, 42]],

       [[42, 42, 42],
        [42, 42, 42]]])

- initialiser une matrice non initialsée de taille 3,3.
empty() est plus rapide que zeros(), mais sans garantie sur les valeurs contenues

In [67]:
np.empty((3,3)) # à ne pas utiliser pour juste créer des cases (valeurs null)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- initialiser une matrice identité de taille 4

In [65]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- créer un tableau avec 7 valeurs réparties équitablement entre 1 et 3.5. Méthode très utilisée pour les graphes, pour échantilloner à intervalle régulier et afficher ces points

In [66]:
np.linspace(1,3.5,7) # génère des valeurs entre 1 et 3.5 sur 7 lignes

array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
       3.08333333, 3.5       ])

- créer un tableau de taille (2,2,3) de chaine de 4 caractère contenant "ynov" dans chaque case. La taille de chaque chaine doit forcément être la même.

In [70]:
np.full((2,2,3), 'bibi')

array([[['bibi', 'bibi', 'bibi'],
        ['bibi', 'bibi', 'bibi']],

       [['bibi', 'bibi', 'bibi'],
        ['bibi', 'bibi', 'bibi']]], dtype='<U4')

conversion entre pandas dataframe et numpy array

In [72]:
import pandas as pd
df = pd.DataFrame([[1,2],[3,4]])
df

0  1
0  1  2
1  3  4

In [73]:
np.array(df)

array([[1, 2],
       [3, 4]])

la premiere dimension encode les lignes :

In [74]:
np.array(df)[0]

array([1, 2])

## 2) Charger et sauvegarder ses valeurs

In [88]:
numpy_array = np.full((1000,1000),42)
numpy_array

array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       ...,
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42]])

- sauvegarder ce tableau

In [89]:
np.save('numpy_array', numpy_array)

- charger le tableau sauvegardé et vérifier qu'il est bien égal au précédent

In [90]:
load_array = np.load('numpy_array.npy')
load_array = numpy_array

- on peut aussi sauvegarder en format compressé. Volume moins important, mais plus long à lire comme necessite decompression. Utilisé pour archiver mais pas pour stocker des données que l'on va utiliser par la suite.

In [91]:
np.savez_compressed('numpy_array', numpy_array)

- on peut sauvegarder et charger plusieurs tableaux dans le même fichier. Utile pour sauvegarder les données et les labels, et garantir qu'on utilise bien les labels correspondants aux données !

In [92]:
arr = np.zeros(3)
np.savez('numpy_arrays', bibi=numpy_array, bibi2=arr)

In [93]:
arrays = np.load('numpy_arrays.npz')

In [97]:
for k in arrays.keys():
    print(k)

bibi
bibi2


In [95]:
arrays['bibi']

array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       ...,
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42]])

In [96]:
arrays['bibi2']

array([0., 0., 0.])

## 3) Obtenir de l'information sur le contenu d'un tableau

- La taille

In [98]:
numpy_array.shape

(1000, 1000)

- le nombre d'element

In [99]:
numpy_array.size

1000000

- le type

In [101]:
numpy_array.dtype

dtype('int64')

On peut changer ce type, pour pouvoir encoder plus de valeurs, faire passer des flottants en entiers ou encore réduire la taille en mémoire d'un tableau.

In [102]:
numpy_array.astype(np.int16)

array([[42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       ...,
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42],
       [42, 42, 42, ..., 42, 42, 42]], dtype=int16)

## 4) Les opérations matricielles

In [130]:
a = np.array([[12,3,4],[0,0,-2]])
b = np.array([[11,2,3],[4,0,2]])
c = np.array([1,2,3])
d = np.array([2,3])

- addition, soustraction

In [105]:
a + b

array([[23,  5,  7],
       [ 4,  0,  0]])

In [106]:
a - b

array([[ 1,  1,  1],
       [-4,  0, -4]])

Attention au résultat si les tableaux n'ont pas la même dimension, cela ne va pas toujours lever des erreurs

In [109]:
a + d

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [112]:
a + c

array([[13,  5,  7],
       [ 1,  2,  1]])

- multiplication et division

In [107]:
a * b

array([[132,   6,  12],
       [  0,   0,  -4]])

In [108]:
a / b

/tmp/ipykernel_3411/1286629031.py:1: RuntimeWarning: invalid value encountered in true_divide
  a / b


array([[ 1.09090909,  1.5       ,  1.33333333],
       [ 0.        ,         nan, -1.        ]])

In [115]:
a * c

array([[12,  6, 12],
       [ 0,  0, -6]])

- la transposée

In [117]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

- le produit matriciel

In [120]:
a.dot(c)

array([14, 32, 50])

Dot d'un vecteur par lui même nous donne sa norme (longueur) au carré

In [122]:
c.dot(c)

14

On peut calculer l'angle entre deux vecteurs avec dot (et arcos)

In [123]:
import math
v1 = np.array((0,1))
v2 = np.array((1,0))
angle = math.acos(v1.dot(v2)/(np.sqrt(v1.dot(v1))+np.sqrt(v2.dot(v2)))) # angle en radian
print("Angle entre v1 et v2 : ", angle/np.pi*180, "degré") # converti en degré

Angle entre v1 et v2 :  90.0 degré


In [124]:
v1.dot(v2)

0

## 5) Comparaison et aggrégations de tableau

- Les comparaisons

In [125]:
a == 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [126]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
a == b

/tmp/ipykernel_3411/160026346.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == b


False

In [128]:
a == a.copy()

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Applications : remplacer par 0 les cases ou a est strictement superieur à b

In [132]:
a[a > b] = 0
a

array([[ 0,  0,  0],
       [ 0,  0, -2]])

Et l'égalité de tableau ?

In [133]:
np.array_equal(a,b)

False

In [134]:
np.array_equal(a,a.copy())

True

In [138]:
a is a.copy() # identique si la référence objet a la même adresse mémoire

False

In [143]:
a is None # utile car impossible de faire a == None

False

- Trier un tableau:

In [146]:
a = np.array([3,2,1])
a.sort()
a

array([1, 2, 3])

- les aggrégations : sum, mean, median, min, max, std,...

In [147]:
b

array([[11,  2,  3],
       [ 4,  0,  2]])

In [148]:
b.mean()

3.6666666666666665

In [149]:
b.sum()

22

In [150]:
b.max()

11

In [151]:
b.min()

0

In [152]:
b.std()

3.4960294939005054

- on peut préciser sur quels axes les appliquer

In [153]:
b

array([[11,  2,  3],
       [ 4,  0,  2]])

In [154]:
b.max(axis=1) # pour appliquer par ligne

array([11,  4])

In [156]:
b.max(axis=0) # pour appliquer par colonne

array([11,  2,  3])

In [158]:
b.sort(axis=1)
b

array([[ 2,  3, 11],
       [ 0,  2,  4]])

In [159]:
b.sort(axis=0)
b

array([[ 0,  2,  4],
       [ 2,  3, 11]])

## 6) accéder aux éléments

In [160]:
b[0,1]

2

In [161]:
b[0][1]

2

3 dimensions ? 

    -> b[0,1,2]
    -> b[0][1][2]

In [162]:
b[1]

array([ 2,  3, 11])

In [163]:
b[b<2]

array([0])

- Slicing. C'est un moyen efficace pour manipuler, acceder et copier plusieurs elements comme il ne demande pas un acces aux elements un par un.

In [165]:
a = np.eye(4)
a[0,2] = 3
a

array([[1., 0., 3., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [166]:
a[1:3]

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [169]:
a[:,1:3] # : prend tout, prend les colonnes 1 à 3

array([[0., 3.],
       [1., 0.],
       [0., 1.],
       [0., 0.]])

In [172]:
a[:,-1]

array([0., 0., 0., 1.])

In [173]:
a[:,1:-1]

array([[0., 3.],
       [1., 0.],
       [0., 1.],
       [0., 0.]])

In [174]:
a[::-1] # change l'ordre des lignes

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 3., 0.]])

In [176]:
a[:,::-1] # change l'ordre des colonnes

array([[0., 3., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [177]:
a[2:4,1:] = b # copie b entre les lignes d'index 2 et 3 et colonnes d'index 1 et plus
a

array([[ 1.,  0.,  3.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  4.],
       [ 0.,  2.,  3., 11.]])

## 7) Autres fonctions pratiques en datascience

- beaucoup de fonctions et utilitaires mathématiques sont présents dans numpy

In [178]:
np.pi

3.141592653589793

In [179]:
np.cos(a)

array([[ 0.54030231,  1.        , -0.9899925 ,  1.        ],
       [ 1.        ,  0.54030231,  1.        ,  1.        ],
       [ 1.        ,  1.        , -0.41614684, -0.65364362],
       [ 1.        , -0.41614684, -0.9899925 ,  0.0044257 ]])

In [180]:
np.sqrt(a)

array([[1.        , 0.        , 1.73205081, 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.41421356, 2.        ],
       [0.        , 1.41421356, 1.73205081, 3.31662479]])

- changer la taille du tableau

In [181]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [182]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [183]:
a.reshape(2,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

- nan et inf values

In [184]:
typical_data = b/b
typical_data[0,2] = np.inf
typical_data[1,2] = None
typical_data

/tmp/ipykernel_3411/4140621361.py:1: RuntimeWarning: invalid value encountered in true_divide
  typical_data = b/b


array([[nan,  1., inf],
       [ 1.,  1., nan]])

- Detecter et remplacer les nan

In [185]:
np.isnan(typical_data)

array([[ True, False, False],
       [False, False,  True]])

In [186]:
np.nan_to_num(typical_data, nan=-1)

array([[-1.00000000e+000,  1.00000000e+000,  1.79769313e+308],
       [ 1.00000000e+000,  1.00000000e+000, -1.00000000e+000]])

- le cas des inf

In [187]:
np.isinf(typical_data)

array([[False, False,  True],
       [False, False, False]])

In [188]:
np.isfinite(typical_data)

array([[False,  True, False],
       [ True,  True, False]])

- remplacer infs et nan par une valeur:

In [189]:
typical_data2 = typical_data.copy()
typical_data2[~np.isfinite(typical_data2)] = 0
typical_data2

array([[0., 1., 0.],
       [1., 1., 0.]])

- remplacer les inf par la valeur maximum non inf :

In [190]:
max = np.max(typical_data[np.isfinite(typical_data)])

In [191]:
typical_data[np.isinf(typical_data)] = max 
typical_data

array([[nan,  1.,  1.],
       [ 1.,  1., nan]])