L'objectif du TP est d'utiliser un réseau de convolution pour classifier le dataset fashion_mnist

In [2]:
import tensorflow.keras as keras
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K


# 1. Chargement du dataset

In [3]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
num_classes = 10


# 2. Conversion du jeu de donnée au format attendu

- Keras attend un format d'image du type (ligne, colonne, channel)
    - combien une image en niveau de gris a de channel ?
    - quelles sont les dimensions des images ?
    - completez input_shape en tant que tuple avec les dimensions correspondantes

In [4]:
img_rows, img_cols = 28, 28
input_shape = (img_rows, img_cols, 1)
x_train = x_train.reshape(
    x_train.shape[0], input_shape[0], input_shape[1], input_shape[2])
x_test = x_test.reshape(
    x_test.shape[0], input_shape[0], input_shape[1], input_shape[2])


- Les réseaux de neurones veulent des entrées proches de zéros

In [5]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255


- Il est très préférable de passer les donnees de sorties au en données catégoriels (1 neurone = présence d'une classe)
    - "onehot encoding" des classes de sorties

In [6]:
print(y_train)


[9 0 0 ... 3 0 5]


In [7]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


In [8]:
print(y_train)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# 3 - Construction du modele

- A votre tour ! Definissez votre réseau de neurones tel que vu en cours
- Commencez simplement (pas beaucoup de couches, optimizer simple)
- Améliorez son architecture en fonction du résultat des premiers entrainements

In [9]:
batch_size = 128


In [10]:
model = Sequential()

# TODO construiser le modele avec les couches vues en cours
# Rappel : model.add(...) permet d'ajouter les couches une par une
# Coup de pouce : je vous ai importé la plupart des couches dont vous aurez besoin au début du notebook

model.add(keras.layers.Conv1D(64, 3, 3, activation='relu',
          input_shape=input_shape, batch_size=batch_size))

model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(
    1, 1), input_shape=input_shape, padding='valid'))
# model.add(Flatten())

model.add(keras.layers.Conv1D(64, 2, 2, activation='relu',
          input_shape=input_shape, batch_size=batch_size))

model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(
    1, 1), input_shape=input_shape, padding='valid'))
model.add(Flatten())

model.add(keras.layers.Dense(84, activation='relu'))
model.add(keras.layers.Dropout(.2))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dropout(.2))
model.add(keras.layers.Dense(10, activation='relu'))


2021-12-16 12:59:22.248059: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-16 12:59:22.249522: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-16 12:59:22.253355: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [11]:
 # TODO choisir la loss, l'optimizer

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer='rmsprop',
              metrics=['accuracy'])


## Entrainement

In [13]:
%%time
# TODO Entrainez votre modèle

epochs = 10
batch_size = 100

model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size,
          validation_data=(x_test, y_test))


Epoch 1/10
600/600 [==============================] - 281s 468ms/step - loss: nan - accuracy: 0.1000 - val_loss: nan - val_accuracy: 0.1000
Epoch 2/10
600/600 [==============================] - 305s 508ms/step - loss: nan - accuracy: 0.1000 - val_loss: nan - val_accuracy: 0.1000
Epoch 3/10
600/600 [==============================] - 307s 512ms/step - loss: nan - accuracy: 0.1000 - val_loss: nan - val_accuracy: 0.1000
Epoch 4/10
600/600 [==============================] - 244s 406ms/step - loss: nan - accuracy: 0.1000 - val_loss: nan - val_accuracy: 0.1000
Epoch 5/10
600/600 [==============================] - 279s 464ms/step - loss: nan - accuracy: 0.1000 - val_loss: nan - val_accuracy: 0.1000
Epoch 6/10
600/600 [==============================] - 249s 415ms/step - loss: nan - accuracy: 0.1000 - val_loss: nan - val_accuracy: 0.1000
Epoch 7/10
600/600 [==============================] - 291s 484ms/step - loss: nan - accuracy: 0.1000 - val_loss: nan - val_accuracy: 0.1000
Epoch 8/10
600/600 [

KeyboardInterrupt: 

### Evaluation

In [ ]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


- En fonction des résultats de validation et d'entrainement, trouvez comment optimiser votre réseau et son entrainement pour améliorer ses performances